import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import News from "@/components/News";
import Wrapper from "@/components/Wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LifeLog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Wrapper>
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between max-w-8xl mx-auto p-4 min-h-screen ">
        <div className="border-r w-[20rem] "><Sidebar/></div>
        <div >{children}</div>
        <div className="border-l w-[29rem]"><News/></div>
        </div>
        </body>
        
    </html>
    </Wrapper>
  );
}
